from typing import Optional
from sentence_transformers.util import cos_sim
from sentence_transformers import SentenceTransformer
import requests
import warnings
import os
from .utils import detect_text, google_lang_translate, language_detection
from lib.data import TestCase, Conversation
from .strategy_base import Strategy
from .logger import get_logger
from .utils_new import FileLoader
import asyncio

warnings.filterwarnings("ignore")

FileLoader._load_env_vars(__file__)
logger = get_logger("language")
dflt_vals = FileLoader._to_dot_dict(__file__, os.getenv("DEFAULT_VALUES_PATH"), simple=True, strat_name="language")

class LanguageStrategies(Strategy):
    def __init__(self, name:str = "language", **kwargs):
        super().__init__(name, **kwargs)
        self.__strategy_name = name
        self.gpu_url=os.getenv("GPU_URL")
        self.embedding_model = SentenceTransformer(dflt_vals.embed_model)
    
    def language_detect_langdetect(self, prompt: str, agent_response: str) -> float:
        """
        Check the language coverage by detecting the language used in the response and comparing it with the expected language. This uses langdetect package.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :return: A score representing if the languages are the same
        """
        logger.info("Evaluating language coverage...")
        response_language = language_detection(agent_response)
        prompt_language = language_detection(prompt)
        score = 1.0 if response_language == prompt_language else 0.0
        logger.info(f"Response language: {response_language}, Prompt language: {prompt_language}, Score: {score}")
        return score

    def language_similarity_sarvam(self, agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Check the language similarity by detecting the language used in the response and comparing it with the expected language. This method uses Sarvam AI.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the language similarity
        """
        logger.info("Evaluating language similarity...")
        response_language = language_detection(agent_response)
        text_list = []
        if response_language !="en":
            response_translated = requests.post(f"{self.gpu_url}/translate",params={"input_text": agent_response,"target_language": response_language})
        else:
            response_translated = agent_response
        expected_language = language_detection(expected_response)
        if expected_language != "en":
            expected_response_translated = requests.post(f"{self.gpu_url}/translate",params={"input_text": expected_response,"target_language": expected_language})
        else:
            expected_response_translated = expected_response
        text_list = [response_translated, expected_response_translated]        
        embeddings = self.embedding_model.encode(text_list)
        similarity = cos_sim(embeddings[0], embeddings[1])
        if similarity>=0.75:
            logger.info("High language similarity detected.")
            score = 1.0
        else:
            logger.info("Low language similarity detected.")
            score = 0.0
        return score

    async def language_detect_gt(self, agent_response: str, expected_response: str) -> float:
        """
        Check the language coverage by detecting the language used in the response and comparing it with the expected language. This uses Google Translate.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :return: A score representing if the languages are the same
        """
        logger.info("Evaluating language coverage...")
        response_language = await detect_text(agent_response)
        expected_language = await detect_text(expected_response)
        score = 1.0 if response_language == expected_language else 0.0
        logger.info(f"Response language: {response_language}, Expected language: {expected_language}, Score: {score}")
        return score

    async def language_similarity_gt(self, agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Check the language similarity by detecting the language used in the response and comparing it with the expected language. This method uses Google translate.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the language similarity
        """
        logger.info("Evaluating language similarity...")
        response_language = await detect_text(agent_response)
        expected_language = await detect_text(expected_response)
        text_list = []
        if response_language !="en":
            response_translated = await google_lang_translate(agent_response)
        else:
            response_translated = agent_response
        if expected_language != "en":
            expected_response_translated = await google_lang_translate(expected_response)
        else:
            expected_response_translated = expected_response
        text_list = [response_translated, expected_response_translated]        
        embeddings = self.embedding_model.encode(text_list)
        similarity = cos_sim(embeddings[0], embeddings[1])
        if similarity>=0.75:
            logger.info("High language similarity detected.")
            score = 1.0
        else:
            logger.info("Low language similarity detected.")
            score = 0.0
        return score
    
    def sync_eval(self, agent_response: str, expected_response: Optional[str] = None):
        match self.__strategy_name:
            case "language_detect_langdetect":
                score = self.language_detect_langdetect(agent_response, expected_response)
                logger.info("Language Detection: %s", score)
                return score
            case "language_similarity_sarvam":
                score = self.language_similarity_sarvam(agent_response, expected_response)
                logger.info("Language Similarity Sarvam: %s", score)
                return score
    
    async def async_eval(self, agent_response: str, expected_response: Optional[str] = None):
        match self.__strategy_name:
            case "language_detect_gt":
                score = await self.language_detect_gt(agent_response, expected_response)
                return score
            case "language_similarity_gt":
                score = await self.language_similarity_gt(agent_response, expected_response)
                return score


    def evaluate(self, testcase:TestCase, conversation:Conversation):
        match self.__strategy_name:
            case "language_detect_langdetect" | "language_similarity_sarvam":
                score =  self.sync_eval(conversation.agent_response, testcase.response.response_text)
                logger.info(f"Score : {score}")
                return score, ""
            case "language_detect_gt" | "language_similarity_gt":
                score =  asyncio.run(self.async_eval(conversation.agent_response, testcase.response.response_text))
                logger.info(f"Score : {score}")
                return score, ""
            case _:
                logger.error(f"Strategy name {self.__strategy_name} is not recognized.")
                raise ValueError(f"Strategy {self.__strategy_name} is not defined.")
        

