import warnings
from lexical_diversity import lex_div
from lib.data import TestCase, Conversation
import os
from .strategy_base import Strategy
from .logger import get_logger
from .utils_new import FileLoader, OllamaConnect

warnings.filterwarnings("ignore")

FileLoader._load_env_vars(__file__)
logger = get_logger("lexicaldiversity")
dflt_vals = FileLoader._to_dot_dict(__file__, os.getenv("DEFAULT_VALUES_PATH"), simple=True, strat_name="lexicaldiversity")

# This module implements lexical diversity to analyze the agent response.
class LexicalDiversity(Strategy):
    def __init__(self, name: str = "lexicaldiversity", **kwargs) -> None:
        super().__init__(name, kwargs=kwargs)

    def lexical_diversity_calculate(self, agent_response: str) -> float:
        """
        Check the lexical diversity in the response
        :param agent_response: The response generated by the agent.
        :return: A score representing the quality of the agent's response.
        """
        logger.info("Evaluating Lexical Diversity...")
        flt = lex_div.flemmatize(agent_response)
        score = lex_div.mattr(flt)
        logger.info(f"lexical_diversity score: {score}")
        return score
    
    def reason_for_score(self, agent_response:str, score:float):
        if(dflt_vals.model_reason):
            try:
                return OllamaConnect.get_reason(agent_response, " ".join(self.name.split("_")), score)
            except:
                logger.error(f"Could not fetch the reason for score. \n Make sure Ollama is running with the specified model, OR change the model_reason to false for {self.name} in data/defaults.json")
                return ""
        else:
            return ""
    
    def evaluate(self, testcase:TestCase, conversation:Conversation):
        """
        Evaluate the agent response for lexical diversity.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against (not used in this strategy).
        :return: A score representing the lexical diversity of the agent's response.
        """
        score = self.lexical_diversity_calculate(conversation.agent_response)
        return score, self.reason_for_score(conversation.agent_response, score)