from abc import ABC, abstractmethod
from typing import Optional
from lib.data import TestCase, Conversation

class Strategy(ABC):
    def __init__(self, name:str, **kwargs) -> None:
        super().__init__()
        self.__name = name
        self.__kwargs = kwargs

    @property
    def name(self) -> str:
        """
        Get the name of the strategy.
        
        :return: The name of the strategy.
        """
        return self.__name

    @abstractmethod
    def evaluate(self, testcase:Optional[TestCase], conversation: Optional[Conversation]) -> tuple[float, str]:
        """
        Evaluate the agent's response against the expected response.
        
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: score the agent's response against the supposed expected response or criteria.
        0.0 means no match, 1.0 means perfect match.
        :return : also return the reason for the score.
        """
        pass