import warnings
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim
import requests
import os
from .utils import language_detection
from lib.data import TestCase, Conversation
from .strategy_base import Strategy
from .logger import get_logger
from .utils_new import FileLoader

warnings.filterwarnings("ignore")

FileLoader._load_env_vars(__file__)
logger = get_logger("transliterated_language_strategy")
dflt_vals = FileLoader._to_dot_dict(__file__, os.getenv("DEFAULT_VALUES_PATH"), simple=True, strat_name="transliterated_language_strategy")

# This module implements ltransliterated languages to analyze the agent response.
class TransliteratedStrategy(Strategy):
    def __init__(self, name: str = "transliterated_language_strategy", **kwargs) -> None:
        super().__init__(name, kwargs=kwargs)
        self.gpu_url = os.getenv("GPU_URL")
        if not self.gpu_url:
            logger.warning("GPU_URL is not set in environment.")
        else:
            logger.info("GPU_URL is loaded from environment.")

    def transliterate_text(self, text: str, expected_response:str) -> float:
        """
        Converts the transliterated text from English to the target language.
        :param text: The text to be transliterated.
        :return: The transliterated text.
        """
        language = language_detection(text)
        if language == "en":
            translated_language = requests.post(f"{self.gpu_url}/translate",params={"input_text": text,"target_language": language})
            sentences = [translated_language, expected_response]
        else:
            sentences = [text, expected_response]

        model = SentenceTransformer(dflt_vals.model_name)
        embeddings = model.encode(sentences)
        similarity = cos_sim(embeddings[0], embeddings[1])
        logger.info("The text similarity is: %s",similarity[0][0].item()) 
        
        return similarity[0][0]
        
    def evaluate(self, testcase:TestCase, conversation:Conversation):
        """
        Evaluate the transliterated text by comparing it with the expected response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the similarity of the transliterated text.
        """
        logger.info("Evaluating transliterated text...")
        score = self.transliterate_text(conversation.agent_response, testcase.response.response_text)
        logger.info(f"Transliterated Score: {score}")
        return score, ""