#@author: Sudarsun
# @date: 2025-06-29
#
# This module defines the Conversation class, which represents a conversation in the AI evaluation system.

from pydantic import BaseModel, Field
from typing import Any, Optional

class Conversation(BaseModel):
    """
    Represents a conversation in the response analysis system.
    Attributes:
        target (str): The name of the target associated with the conversation.
        testcase (str): The name of the test case associated with the conversation.
        agent_response (str): The response generated by the AI agent.
        prompt_ts (str): ISO Timestamp when the test case prompt was sent.
        response_ts (str): ISO Timestamp when the agent response was received.
        evaluation_score (float): The evaluation score assigned to the agent response.
        evaluation_reason (str): The reason or explanation for the evaluation score.
        evaluation_ts (str): ISO Timestamp when the evaluation was performed.
        kwargs (dict): Additional keyword arguments for future extensibility.
    """
    target: str = Field(..., description="The name of the target associated with the conversation.")
    testcase: str = Field(..., description="The name of the test case associated with the conversation.")
    run_detail_id: int = Field(..., description="The ID of the run detail associated with this conversation.")
    agent_response: Optional[str] = Field(None, description="The response generated by the AI agent.")
    prompt_ts: Optional[str] = Field(None, description="ISO Timestamp when the test case prompt was sent.")
    response_ts: Optional[str] = Field(None, description="ISO Timestamp when the AI agent response was received.")
    evaluation_score: Optional[float] = Field(None, description="The evaluation score assigned to the agent response.")
    evaluation_reason: Optional[str] = Field(None, description="The reason or explanation for the evaluation score.")
    evaluation_ts:Optional[str] = Field(None, description="ISO Timestamp when the evaluation was performed.")
    kwargs: dict = Field(default_factory=dict, description="Additional keyword arguments for future extensibility")

    def __init__(self, target: str, run_detail_id: int, testcase: str, agent_response: Optional[str] = None, prompt_ts: Optional[str] = None, response_ts: Optional[str] = None,
                 evaluation_score: Optional[float] = None, evaluation_reason: Optional[str] = None, evaluation_ts: Optional[str] = None, **kwargs):
        """
        Initializes a Conversation instance.
        Args:
            target (str): The name of the target associated with the conversation.
            testcase (str): The name of the test case associated with the conversation.
            agent_response (str): The response generated by the AI agent.
            prompt_ts (str): ISO Timestamp when the test case prompt was sent.
            response_ts (str): ISO Timestamp when the agent response was received.
            kwargs: Additional keyword arguments for future extensibility.
        """
        super().__init__(target=target, run_detail_id=run_detail_id, testcase=testcase, agent_response=agent_response, prompt_ts=prompt_ts, response_ts=response_ts,
                         evaluation_score=evaluation_score, evaluation_reason=evaluation_reason, evaluation_ts=evaluation_ts, kwargs=kwargs)

    def __getattr__(self, name: str) -> Any:
        """
        Allows access to additional keyword arguments as attributes.
        If the attribute does not exist, raises an AttributeError.
        Args:
            name (str): The name of the attribute to access.
        Returns:
            Any: The value of the attribute if it exists in kwargs.
        Raises:
            AttributeError: If the attribute does not exist in kwargs.
        """
        if name.startswith('_') or name not in self.kwargs:
            raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")
        return self.kwargs.get(name)

    def __repr__(self):
        return f"Conversation(target='{self.target}', testcase='{self.testcase}')"
    
    def __str__(self):
        return f"Conversation with target: '{self.target}'\tTest case: '{self.testcase}'\tAgent response: '{self.agent_response}'\tPrompt timestamp: '{self.prompt_ts}'\tResponse timestamp: '{self.response_ts}'\tEvaluation score: '{self.evaluation_score}'\tEvaluation reason: '{self.evaluation_reason}'\tEvaluation timestamp: '{self.evaluation_ts}'"

    def __eq__(self, other):
        """
        Compares two Conversation instances for equality.
        Args:
            other (Conversation): The other Conversation instance to compare with.
        Returns:
            bool: True if both instances are equal, False otherwise.
        """
        if not isinstance(other, Conversation):
            return NotImplemented
        return (self.target == other.target and
                self.testcase == other.testcase and
                self.agent_response == other.agent_response and
                self.prompt_ts == other.prompt_ts and
                self.response_ts == other.response_ts and
                self.evaluation_score == other.evaluation_score and
                self.evaluation_reason == other.evaluation_reason and
                self.evaluation_ts == other.evaluation_ts)

    def __hash__(self):
        """
        Returns a hash value for the Conversation instance.
        This is used to allow Conversation instances to be used as keys in dictionaries or added to sets.
        Returns:
            int: The hash value of the instance.
        """
        return hash((self.target, self.testcase, self.agent_response, self.prompt_ts, self.response_ts, self.evaluation_score, self.evaluation_reason, self.evaluation_ts))
